[project]
name = "mauren"
version = "0.3.0"
description = "Client for interacting with the Mau server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
